name: Copy to WebCV

on:
  push:
    branches:    
      - 'main'
    paths:
      - 'install.sh'

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes install file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'install.sh'
        destination_repo: 'MrCitron/WebCV'
        user_email: '41898282+github-actions[bot]@users.noreply.github.com'
        user_name: 'github-actions[bot]'
        commit_message: 'Update install.sh script from https://github.com/MrCitron/dotfiles'